type CommunityPost {
  _id: String
  content: String
  datePublished: String
  owner: User
}

input CommunityPostCreateInp {
  _id: String
}

input CommunityPostUpdateInp {
  _id: String
}

input CommunityPostRDInp {
  _id: String
}
