type Post {
  _id: String!
  title: String!
  description: String!
  content: String!
  comments: [String!]!
  tags: [String!]!
  stats: PostStats!
  datePublished: String!
  dateUpdated: String!
}

type PostStats {
  views: Int!
  likes: Int!
  appreciations: Int!
  applauds: Int!
}

input PostRDInp {
  _id: String!
}

input PostCreateInp {
  title: String!
  description: String!
  content: String!
  tags: [String!]!
}

input PostUpdateInp {
  _id: String!
  title: String
  description: String
  content: String
  tags: [String]
}
