type Publication {
  _id: String!
  name: String!
  cover: String!
  profileImg: String!
  featuredImg: String!
  posts: [Post!]!
  collections: [[String!]!]!  # TODO: Create a new model of collection
  papers: [Paper!]!
  followers: [User!]!
  owners: [User!]!
  members: [User!]!
  dateCreated: String!
  dateUpdated: String!
}

input getPublicationRDInp {
  _id: String!
}

input createPublication {
  name: String!
  cover: String!
  profileImg: String!
  owners: [String!]!
  members: [String!]!
}

input updatePublication {
  name: String
  cover: String
  profileImg: String
  featuredImg: String
  posts: [String!]
  collections: [[String!]!]
  papers: [String!]
  owners: [String!]
  members: [String!]
}
