# import Collection, CollectionRDInp, CollectionCreateInp, CollectionUpdateInp from "./collections.gql"
# import CommunityPost, CommunityPostRDInp, CommunityPostCreateInp, CommunityPostUpdateInp from "./community-posts.gql"
# import Merchandise, MerchandiseRDInp, MerchandiseCreateInp, MerchandiseUpdateInp from "./merchandises.gql"
# import Post, PostRDInp, PostCreateInp, PostUpdateInp from "./posts.gql"
# import Publication, PublicationRDInp, PublicationCreateInp, PublicationUpdateInp from "./publications.gql"
# import Story, StoryRDInp, StoryCreateInp from "./story.gql"
# import User, UserRDInp, UserCreateInp, UserUpdateInp from "./users.gql"
# import Paper from "./paper.gql"
# import getNewRavelsInp, getFeaturedUserInp, Trending from "./tools.gql"

scalar JSON

type QueryResolver {
  getCollection(args: CollectionRDInp): Collection
  getCommunityPost(args: CommunityPostRDInp): CommunityPost
  getMerchandise(args: MerchandiseRDInp): Merchandise
  getPost(args: PostRDInp): Post
  getPublication(args: PublicationRDInp): Publication
  getStory(args: StoryRDInp): Story
  getUser(args: UserRDInp): User
  # Other tools
  getNewRavels(args: getNewRavelsInp): [Post]
  getUserRecommendations(args: getUserRecommendationsInp): [Post]
  getTrending: Trending
  getExplore: Explore
  getFeaturedUser(args: getFeaturedUserInp): User
}

type MutationResolver {
  # Collection
  createCollection(args: CollectionCreateInp): Boolean
  updateCollection(args: CollectionUpdateInp): Boolean
  deleteCollection(args: CollectionRDInp): Boolean
  # CommunityPost
  createCommunityPost(args: CommunityPostCreateInp): Boolean
  updateCommunityPost(args: CommunityPostUpdateInp): Boolean
  deleteCommunityPost(args: CommunityPostRDInp): Boolean
  # Merchandise
  createMerchandise(args: MerchandiseCreateInp): Boolean
  updateMerchandise(args: MerchandiseUpdateInp): Boolean
  deleteMerchandise(args: MerchandiseRDInp): Boolean
  # Post
  createPost(args: PostCreateInp): Boolean
  updatePost(args: PostUpdateInp): Boolean
  deletePost(args: PostRDInp): Boolean
  # Publication
  createPublication(args: PublicationCreateInp): Boolean
  updatePublication(args: PublicationUpdateInp): Boolean
  deletePublication(args: PublicationRDInp): Boolean
  # Story
  createStory(args: StoryCreateInp): Boolean
  deleteStory(args: StoryRDInp): Boolean
  # User
  createUser(args: UserCreateInp): Boolean
  updateUser(args: UserUpdateInp): Boolean
  deleteUser(args: UserRDInp): Boolean
}

schema {
  query: QueryResolver
  mutation: MutationResolver
}
