# import Post, PostRDInp, PostCreateInp, PostUpdateInp from "./posts.gql"
# import Story, StoryRDInp, StoryCreateInp, StoryUpdateInp from "./story.gql"
# import Merchandise, MerchandiseRDInp, MerchandiseCreateInp, MerchandiseUpdateInp from "./merchandises.gql"
# import User, UserRDInp, UserCreateInp, UserUpdateInp from "./users.gql"
# import CommunityPost, CommunityPostRDInp from "./community-posts.gql"
# import Publication, PublicationRDInp, PublicationCreateInp, PublicationUpdateInp from "./publications.gql"
# import Collection, CollectionRDInp from "./collections.gql"
# import Paper from "./paper.gql"
# import getNewRavelsInp, getFeaturedUserInp, Trending from "./tools.gql"

scalar JSON

type QueryResolver {
  getPost(args: PostRDInp): Post
  getStory(args: StoryRDInp): Story
  getMerchandise(args: MerchandiseRDInp): Merchandise
  getUser(args: UserRDInp): User
  getCommunityPost(args: CommunityPostRDInp): CommunityPost
  getPublication(args: getPublicationRDInp): Publication
  getCollection(args: getCollectionRDInp): Collection
  # Other tools
  getNewRavels(args: getNewRavelsInp): [Post]
  getUserRecommendations(args: getUserRecommendationsInp): [Post]
  getTrending: Trending
  getExplore: Explore
  getFeaturedUser(args: getFeaturedUserInp): User
}

type MutationResolver {
  # Post
  deletePost(args: PostRDInp): Boolean
  createPost(args: PostCreateInp): Boolean
  updatePost(args: PostUpdateInp): Boolean
  # Story
  deleteStory(args: StoryRDInp): Boolean
  createStory(args: StoryCreateInp): Boolean
  # Merchandise
  deleteMerchandise(args: MerchandiseRDInp): Boolean
  createMerchandise(args: MerchandiseCreateInp): Boolean
  updateMerchandise(args: MerchandiseUpdateInp): Boolean
  # User
  deleteUser(args: UserRDInp): Boolean
  createUser(args: UserCreateInp): Boolean
  updateUser(args: UserUpdateInp): Boolean
}

schema {
  query: QueryResolver
  mutation: MutationResolver
}
