type Story {
  _id: String!
  content: String!
  stats: StoryStats!
  datePublished: String!
  comments: [String!]!
}

type StoryStats {
  views: Int!
  likes: Int!
  appreciations: Int!
  applauds: Int!
}

input StoryRDInp {
  _id: String!
}

input StoryCreateInp {
  content: String!
}
