type User {
  _id: String!
  history: [String!]!
  saved: [String!]!
  data: UserData!
}

type UserData {
  uname: String!
  pword: String!
  email: String!
  gender: String!
  coverImg: String!
  profileImg: String!
  name: String!
  bio: String!
  isSuspended: Boolean!
  socialLinks: [String!]!
  memberOf: [Publication!]!
  posts: UserPosts!
  stories: [Story]!
  followers: [User]!
  following: [User]!
  stats: UserStats!
  merchandise: [Merchandise]!
}

type UserStats {
  reach: Int!
  appreciations: Int!
}

type UserPosts {
  categories: [String!]!
  posts: [Post!]!
  featuredPosts: Post!
}

input UserRDInp {
  _id: String!
}

input UserCreateInp {
  uname: String!
  name: String!
  pword: String!
  email: String!
  gender: String!
  coverImg: String
  profileImg: String
  bio: String
  socialLinks: [String!]
}

input UserUpdateInp {
  _id: String!
  name: String
  pword: String
  email: String
  gender: String
  profileImg: String
  coverImg: String
  description: String
  socialLinks: [String!]
  content: String
  tags: [String]
  merchandise: [String!]
}
